const MCQ_DATA = [
  // --- Choose the correct answer (MCQ) ---
  { id: 1, type: 'mcq', question: "What does the OSI abbreviation stand for?", options: ["A) Open Serial Interconnect", "B) Open System Interconnection", "C) Only Serial Internet", "D) Only System Interconnect"], answer: "B" },
  { id: 2, type: 'mcq', question: "How many layers are there in the OSI model?", options: ["A) 4 layers", "B) 5 layers", "C) 6 layers", "D) 7 layers"], answer: "D" },
  { id: 3, type: 'mcq', question: "How many layers are there in the TCP/IP model?", options: ["A) 4 layers", "B) 5 layers", "C) 6 layers", "D) 7 layers"], answer: "A" },
  { id: 4, type: 'mcq', question: "Which of the following layers is looking for the appropriate protocol to support the user's process?", options: ["A) Presentation layer", "B) Session layer", "C) Transport layer", "D) Application layer"], answer: "D" },
  { id: 5, type: 'mcq', question: "At what layer is data encrypted and decrypted?", options: ["A) Presentation layer", "B) Session layer", "C) Transport layer", "D) Application layer"], answer: "A" },
  { id: 6, type: 'mcq', question: "At which layer does the authentication and authorization process take place?", options: ["A) Presentation layer", "B) Session layer", "C) Transport layer", "D) Application layer"], answer: "B" },
  { id: 7, type: 'mcq', question: "To which layer do the TCP and UDP protocols belong?", options: ["A) Presentation layer", "B) Session layer", "C) Transport layer", "D) Application layer"], answer: "C" },
  { id: 8, type: 'mcq', question: "At which layer is the best path chosen for the transmission of data?", options: ["A) Presentation layer", "B) Session layer", "C) Network layer", "D) Application layer"], answer: "C" },
  { id: 9, type: 'mcq', question: "At which layer do the data encapsulation and decapsulation processes take place?", options: ["A) Data link layer", "B) Session layer", "C) Network layer", "D) Application layer"], answer: "A" },
  { id: 10, type: 'mcq', question: "At which layer is the data transformed, depending on the type of transmission channel?", options: ["A) Data link layer", "B) Physical layer", "C) Network layer", "D) Application layer"], answer: "B" },
  { id: 11, type: 'mcq', question: "Which of the following devices perform broadcasting on the network?", options: ["A) Switch", "B) Router", "C) Hub", "D) Bridge"], answer: "C" },
  { id: 12, type: 'mcq', question: "Which device is responsible for routing data between different networks?", options: ["A) Switch", "B) Router", "C) Hub", "D) Bridge"], answer: "B" },
  { id: 13, type: 'mcq', question: "Which device can boost the signal in networks?", options: ["A) Switch", "B) Repeater", "C) Router", "D) Firewall"], answer: "B" },
  { id: 14, type: 'mcq', question: "What device is used to protect the network and prevent unauthorized access?", options: ["A) Router", "B) Switch", "C) Firewall", "D) Hub"], answer: "C" },
  { id: 15, type: 'mcq', question: "What device is used to connect wireless devices to the network?", options: ["A) Switch", "B) Router", "C) Access Point", "D) Bridge"], answer: "C" },
  { id: 16, type: 'mcq', question: "Which device is typically used to connect two LAN networks?", options: ["A) Bridge", "B) Hub", "C) Modem", "D) Repeater"], answer: "A" },
  { id: 17, type: 'mcq', question: "Which device relies on the MAC address to make the decision to send data?", options: ["A) Router", "B) Switch", "C) Modem", "D) Repeater"], answer: "B" },
  { id: 18, type: 'mcq', question: "Which topology is based on a central device?", options: ["A) Bus", "B) Ring", "C) Star", "D) Mesh"], answer: "C" },
  { id: 19, type: 'mcq', question: "In what type of network does the failure of just one cable cause the entire network to fail?", options: ["A) Star", "B) Ring", "C) Mesh", "D) Hybrid"], answer: "B" },
  { id: 20, type: 'mcq', question: "Which topology is based on a single main cable (backbone)?", options: ["A) Star", "B) Ring", "C) Bus", "D) Mesh"], answer: "C" },
  { id: 21, type: 'mcq', question: "Which topology has the highest fault tolerance?", options: ["A) Bus", "B) Star", "C) Ring", "D) Mesh"], answer: "D" },
  { id: 22, type: 'mcq', question: "Which topology is most costly to implement due to the large number of cables?", options: ["A) Bus", "B) Star", "C) Ring", "D) Mesh"], answer: "D" },
  { id: 23, type: 'mcq', question: "Which topology allows for more than one path between devices?", options: ["A) Bus", "B) Ring", "C) Star", "D) Mesh"], answer: "D" },
  { id: 24, type: 'mcq', question: "Which topology is a combination of more than one topology?", options: ["A) Ring", "B) Star", "C) Bus", "D) Hybrid"], answer: "D" },
  { id: 25, type: 'mcq', question: "Which Topology needs Terminators?", options: ["A) Star", "B) Ring", "C) Bus", "D) Mesh"], answer: "C" },
  { id: 26, type: 'mcq', question: "The function of an IP address is:", options: ["A) Device type identification", "B) Device location identification on the network", "C) Network speed identification", "D) Data Encryption"], answer: "B" },
  { id: 27, type: 'mcq', question: "Which of the following is a valid IPv4 address?", options: ["A) 192.168.300.1", "B) 172.16.1", "C) 10.0.0.1", "D) 256.1.1.1"], answer: "C" },
  { id: 28, type: 'mcq', question: "IPv4 consists of:", options: ["A) 16 bit", "B) 32 bit", "C) 64 bit", "D) 128 bit"], answer: "B" },
  { id: 29, type: 'mcq', question: "Which Subnet Mask use for a Class C network?", options: ["A) 255.0.0.0", "B) 255.255.0.0", "C) 255.255.255.0", "D) 255.255.255.252"], answer: "C" },
  { id: 30, type: 'mcq', question: "What is the function of a Subnet Mask?", options: ["A) Determining connection speed", "B) Dividing the network into smaller networks", "C) Encrypting IP addresses", "D) Preventing attacks"], answer: "B" },
  { id: 31, type: 'mcq', question: "Which IP address is considered private?", options: ["A) 8.8.8.8", "B) 1.1.1.1", "C) 192.168.1.10", "D) 172.40.1.1"], answer: "C" },
  { id: 32, type: 'mcq', question: "Which class starts with the number 10?", options: ["A) Class A", "B) Class B", "C) Class C", "D) Class D"], answer: "A" },
  { id: 33, type: 'mcq', question: "Which of the following is a correct Subnet Mask?", options: ["A) 255.255.0.255", "B) 255.255.255.128", "C) 255.0.255.0", "D) 256.255.255.0"], answer: "B" },
  { id: 34, type: 'mcq', question: "If we have an IPv4 192.168.1.1 and a subnet mask 255.255.255.0, the network ID is:", options: ["A) 192.168.1.1", "B) 192.168.1", "C) 192.168", "D) 192"], answer: "B" },
  { id: 35, type: 'mcq', question: "If we have an IPv4 172.16.1.5 and a subnet mask 255.255.0.0, the host ID is:", options: ["A) 172.16.1.5", "B) 16.1.5", "C) 1.5", "D) 5"], answer: "C" },
  { id: 36, type: 'mcq', question: "If the subnet mask is 255.255.255.0, the number of hosts is?", options: ["A) 254", "B) 256", "C) 255", "D) 128"], answer: "A" },
  { id: 37, type: 'mcq', question: "Which address cannot be assigned to a device?", options: ["A) Network Address", "B) Broadcast Address", "C) a and b", "D) Nothing"], answer: "C" },
  { id: 38, type: 'mcq', question: "Which of the following is a Loopback Address?", options: ["A) 192.168.1.1", "B) 10.0.0.1", "C) 127.0.0.1", "D) 0.0.0.0"], answer: "C" },
  { id: 39, type: 'mcq', question: "Which of the following protocols is responsible for the process of sending email messages?", options: ["A) SMTP", "B) POP3", "C) IMAP", "D) FTP"], answer: "A" },
  { id: 40, type: 'mcq', question: "Which of the following protocols is responsible for the process of receiving email messages?", options: ["A) SMTP", "B) POP3", "C) IMAP", "D) b and c"], answer: "D" },
  { id: 41, type: 'mcq', question: "Which of the following protocols allows you to control devices remotely?", options: ["A) Telnet", "B) SSH", "C) DNS", "D) a and b"], answer: "D" },
  { id: 42, type: 'mcq', question: "Which of the following protocols is responsible for uploading and downloading files?", options: ["A) FTP", "B) HTTP", "C) DHCP", "D) DNS"], answer: "A" },
  { id: 43, type: 'mcq', question: "Which of the following protocols is used to dynamically assign IP addresses to devices on a network?", options: ["A) FTP", "B) SSH", "C) DNS", "D) DHCP"], answer: "D" },
  { id: 44, type: 'mcq', question: "Which of the following protocols is used to browse web pages?", options: ["A) DHCP", "B) Telnet", "C) HTTP", "D) SMTP"], answer: "C" },
  { id: 45, type: 'mcq', question: "Which of the following protocols is used to encrypt browsing data to make browsing more secure?", options: ["A) HTTP", "B) HTTPS", "C) SSH", "D) FTPS"], answer: "B" },

  // --- True/False Questions ---
  { id: 46, type: 'tf', question: "A switch uses MAC addresses to forward data.", options: ["A) True", "B) False"], answer: "A" },
  { id: 47, type: 'tf', question: "A repeater is used to strengthen network signals.", options: ["A) True", "B) False"], answer: "A" },
  { id: 48, type: 'tf', question: "A firewall is used to secure a network.", options: ["A) True", "B) False"], answer: "A" },
  { id: 49, type: 'tf', question: "Star topology depends on a central device.", options: ["A) True", "B) False"], answer: "A" },
  { id: 50, type: 'tf', question: "Ring topology is easy to expand.", options: ["A) True", "B) False"], answer: "B" },
  { id: 51, type: 'tf', question: "Bus topology uses a single backbone cable.", options: ["A) True", "B) False"], answer: "A" },
  { id: 52, type: 'tf', question: "Mesh topology is cheaper than star topology.", options: ["A) True", "B) False"], answer: "B" },
  { id: 53, type: 'tf', question: "In star topology, cable failure affects only one device.", options: ["A) True", "B) False"], answer: "A" },
  { id: 54, type: 'tf', question: "An IP address identifies a device on a network.", options: ["A) True", "B) False"], answer: "A" },
  { id: 55, type: 'tf', question: "IPv4 consists of 64 bits.", options: ["A) True", "B) False"], answer: "B" },
  { id: 56, type: 'tf', question: "192.168.1.1 is a private IP address.", options: ["A) True", "B) False"], answer: "A" },
  { id: 57, type: 'tf', question: "A subnet mask is used to divide a network into smaller networks.", options: ["A) True", "B) False"], answer: "A" },
  { id: 58, type: 'tf', question: "255.255.255.0 is a subnet mask for Class C networks.", options: ["A) True", "B) False"], answer: "A" },
  { id: 59, type: 'tf', question: "A network address can be assigned to a host.", options: ["A) True", "B) False"], answer: "B" },
  { id: 60, type: 'tf', question: "The broadcast address is the last address in a subnet.", options: ["A) True", "B) False"], answer: "A" },
  { id: 61, type: 'tf', question: "A /24 network provides 256 usable host addresses.", options: ["A) True", "B) False"], answer: "B" },
  { id: 62, type: 'tf', question: "127.0.0.1 is known as the loopback address.", options: ["A) True", "B) False"], answer: "A" },
  { id: 63, type: 'tf', question: "The default gateway is the network address.", options: ["A) True", "B) False"], answer: "B" },
  { id: 64, type: 'tf', question: "TCP is a reliable protocol that guarantees data delivery.", options: ["A) True", "B) False"], answer: "A" },
  { id: 65, type: 'tf', question: "UDP is slower than TCP.", options: ["A) True", "B) False"], answer: "B" },
  { id: 66, type: 'tf', question: "TCP uses acknowledgments.", options: ["A) True", "B) False"], answer: "A" },
  { id: 67, type: 'tf', question: "UDP is suitable for real-time applications.", options: ["A) True", "B) False"], answer: "A" },
  { id: 68, type: 'tf', question: "TCP does not guarantee packet order.", options: ["A) True", "B) False"], answer: "B" },
  { id: 69, type: 'tf', question: "HTTP transmits data in encrypted form.", options: ["A) True", "B) False"], answer: "B" },
  { id: 70, type: 'tf', question: "HTTPS uses SSL/TLS encryption.", options: ["A) True", "B) False"], answer: "A" },
  { id: 71, type: 'tf', question: "HTTPS is more secure than HTTP.", options: ["A) True", "B) False"], answer: "A" },
  { id: 72, type: 'tf', question: "HTTP uses port 80.", options: ["A) True", "B) False"], answer: "A" },
  { id: 73, type: 'tf', question: "FTP is an unencrypted protocol.", options: ["A) True", "B) False"], answer: "A" },
  { id: 74, type: 'tf', question: "FTPS uses SSL/TLS for encryption.", options: ["A) True", "B) False"], answer: "A" },
  { id: 75, type: 'tf', question: "SFTP is based on SSH.", options: ["A) True", "B) False"], answer: "A" },
  { id: 76, type: 'tf', question: "FTP is considered a secure protocol.", options: ["A) True", "B) False"], answer: "B" },
  { id: 77, type: 'tf', question: "Telnet transmits data in plain text.", options: ["A) True", "B) False"], answer: "A" },
  { id: 78, type: 'tf', question: "Telnet is more secure than SSH.", options: ["A) True", "B) False"], answer: "B" },
  { id: 79, type: 'tf', question: "SSH is widely used for secure remote access.", options: ["A) True", "B) False"], answer: "A" },
  { id: 80, type: 'tf', question: "Telnet is not recommended for modern networks.", options: ["A) True", "B) False"], answer: "A" },
  { id: 81, type: 'tf', question: "POP3 stores emails on the server by default.", options: ["A) True", "B) False"], answer: "B" },
  { id: 82, type: 'tf', question: "IMAP allows email access from multiple devices.", options: ["A) True", "B) False"], answer: "A" },
  { id: 83, type: 'tf', question: "IMAP is more flexible than POP3.", options: ["A) True", "B) False"], answer: "A" },
  { id: 84, type: 'tf', question: "POP3 downloads emails to the local device.", options: ["A) True", "B) False"], answer: "A" },
  { id: 85, type: 'tf', question: "NIC allows a device to connect to a network.", options: ["A) True", "B) False"], answer: "A" },
  { id: 86, type: 'tf', question: "NIC does not have an MAC address.", options: ["A) True", "B) False"], answer: "B" },
  { id: 87, type: 'tf', question: "A NIC can be wired or wireless.", options: ["A) True", "B) False"], answer: "A" },
  { id: 88, type: 'tf', question: "NIC is responsible for sending and receiving data.", options: ["A) True", "B) False"], answer: "A" }
  ];

const QUESTIONS = [
  ...MCQ_DATA
];