const MCQ_DATA = [
  // Lecture 1: Introduction to Computer Networks
  { id: 1, question: "1) Which of the following is considered part of the 'Network Edge'?", options: ["A) Routers", "B) Switches", "C) End systems (Hosts)", "D) Fiber optic cables"], answer: "C" },
  { id: 2, question: "2) Protocols define the format and order of messages sent and received among network entities.", options: ["A) True", "B) False"], answer: "A" },
  { id: 3, question: "3) In DSL, data is transmitted over which existing infrastructure?", options: ["A) Cable TV lines", "B) Telephone lines", "C) Satellite links", "D) Power lines"], answer: "B" },
  { id: 4, question: "4) Packet-switching uses 'Store-and-Forward' transmission.", options: ["A) True", "B) False"], answer: "A" },
  { id: 5, question: "5) Which switching method reserves a dedicated end-to-end resource (circuit) for a call?", options: ["A) Packet switching", "B) Message switching", "C) Circuit switching", "D) Hybrid switching"], answer: "C" },
  { id: 6, question: "6) Frequency Division Multiplexing (FDM) shares the transmission medium by dividing it into different time slots.", options: ["A) True", "B) False"], answer: "B" },
  { id: 7, question: "7) What is the main advantage of packet switching over circuit switching?", options: ["A) Guaranteed bandwidth", "B) Lower delay", "C) Better sharing of resources (Efficient)", "D) Simplicity"], answer: "C" },
  { id: 8, question: "8) A Tier-1 ISP provides national and international coverage and connects directly to other Tier-1 ISPs.", options: ["A) True", "B) False"], answer: "A" },
  { id: 9, question: "9) What does RFC stand for in Internet standards?", options: ["A) Ready for Communication", "B) Request for Comments", "C) Router Forwarding Control", "D) Random Frequency Channel"], answer: "B" },
  { id: 10, question: "10) In packet switching, if the arrival rate to a link exceeds the link capacity for a period of time, packets will be queued.", options: ["A) True", "B) False"], answer: "A" },
  { id: 11, question: "11) Which access network is typically shared by many users in a neighborhood?", options: ["A) DSL", "B) Cable Network (HFC)", "C) Dial-up", "D) Enterprise LAN"], answer: "B" },
  { id: 12, question: "12) 'Statistical Multiplexing' is used in circuit switching.", options: ["A) True", "B) False"], answer: "B" },
  { id: 13, question: "13) What is the unit of data in packet switching?", options: ["A) Circuit", "B) Bit", "C) Packet", "D) Slot"], answer: "C" },
  { id: 14, question: "14) An IXP (Internet Exchange Point) is where different ISPs interconnect.", options: ["A) True", "B) False"], answer: "A" },
  { id: 15, question: "15) Guided media involves signals propagating in solid media like copper or fiber.", options: ["A) True", "B) False"], answer: "A" },
  { id: 16, question: "16) Which of the following is NOT an end system?", options: ["A) Smartphone", "B) Web Server", "C) Router", "D) Laptop"], answer: "C" },
  { id: 17, question: "17) TDM stands for Time Division Multiplexing.", options: ["A) True", "B) False"], answer: "A" },
  { id: 18, question: "18) What happens in circuit switching if a user does not send data during their reserved time?", options: ["A) The resource is given to another user", "B) The resource is wasted", "C) The transmission speed increases", "D) The connection is terminated"], answer: "B" },
  { id: 19, question: "19) Packet switching can allow more users to use the network compared to circuit switching.", options: ["A) True", "B) False"], answer: "A" },
  { id: 20, question: "20) The 'Network Core' is primarily a mesh of interconnected routers.", options: ["A) True", "B) False"], answer: "A" },

  // Lecture 2: Physical Media & Layering Models
  { id: 21, question: "1) Which twisted-pair category is commonly used for 10Gbps Ethernet?", options: ["A) Cat 3", "B) Cat 5", "C) Cat 6", "D) Cat 1"], answer: "C" },
  { id: 22, question: "2) Fiber optic cable is immune to electromagnetic interference (EMI).", options: ["A) True", "B) False"], answer: "A" },
  { id: 23, question: "3) What is the PDU (Protocol Data Unit) of the Transport Layer?", options: ["A) Frame", "B) Datagram/Packet", "C) Segment", "D) Bit"], answer: "C" },
  { id: 24, question: "4) The OSI model consists of 5 layers.", options: ["A) True", "B) False"], answer: "B" },
  { id: 25, question: "5) Which layer is responsible for routing datagrams from source to destination?", options: ["A) Physical Layer", "B) Network Layer", "C) Transport Layer", "D) Application Layer"], answer: "B" },
  { id: 26, question: "6) Encapsulation happens at the source, while Decapsulation happens at the destination.", options: ["A) True", "B) False"], answer: "A" },
  { id: 27, question: "7) Which layer in the Internet stack (TCP/IP) deals with bits 'on the wire'?", options: ["A) Link Layer", "B) Network Layer", "C) Physical Layer", "D) Presentation Layer"], answer: "C" },
  { id: 28, question: "8) Coaxial cable can carry multiple channels at different frequencies (broadband).", options: ["A) True", "B) False"], answer: "A" },
  { id: 29, question: "9) What is added to the data at each layer during encapsulation?", options: ["A) Payload", "B) Trailer only", "C) Header", "D) Nothing"], answer: "C" },
  { id: 30, question: "10) Radio is considered a 'Guided' transmission medium.", options: ["A) True", "B) False"], answer: "B" },
  { id: 31, question: "11) Which OSI layer is responsible for encryption and compression?", options: ["A) Session Layer", "B) Presentation Layer", "C) Application Layer", "D) Transport Layer"], answer: "B" },
  { id: 32, question: "12) Ethernet and WiFi operate at the Link Layer.", options: ["A) True", "B) False"], answer: "A" },
  { id: 33, question: "13) What is the correct order of the TCP/IP layers from top to bottom?", options: ["A) Network, Transport, Link, Physical, Application", "B) Application, Transport, Network, Link, Physical", "C) Physical, Link, Network, Transport, Application", "D) Application, Network, Transport, Link, Physical"], answer: "B" },
  { id: 34, question: "14) A switch usually processes up to the Link layer.", options: ["A) True", "B) False"], answer: "A" },
  { id: 35, question: "15) Twisted pair (TP) consists of two insulated copper wires.", options: ["A) True", "B) False"], answer: "A" },
  { id: 36, question: "16) Which media has the lowest error rate over long distances?", options: ["A) Twisted Pair", "B) Coaxial Cable", "C) Fiber Optic", "D) Radio"], answer: "C" },
  { id: 37, question: "17) In the OSI model, the Session layer is layer number 5.", options: ["A) True", "B) False"], answer: "A" },
  { id: 38, question: "18) IP (Internet Protocol) belongs to the Transport layer.", options: ["A) True", "B) False"], answer: "B" },
  { id: 39, question: "19) A router is considered a 'Layer 3' device.", options: ["A) True", "B) False"], answer: "A" },
  { id: 40, question: "20) Naming and addressing (like IP addresses) are used for encapsulation headers.", options: ["A) True", "B) False"], answer: "A" },

  // Lecture 3: Performance & HTTP
  { id: 41, question: "1) Which delay component depends on the distance between two routers?", options: ["A) Transmission delay", "B) Propagation delay", "C) Queuing delay", "D) Processing delay"], answer: "B" },
  { id: 42, question: "2) Transmission delay is calculated as L / R (Packet length / Link bandwidth).", options: ["A) True", "B) False"], answer: "A" },
  { id: 43, question: "3) Traffic intensity (L * a / R) should be greater than 1 for a stable network.", options: ["A) True", "B) False"], answer: "B" },
  { id: 44, question: "4) HTTP is a 'Stateless' protocol.", options: ["A) True", "B) False"], answer: "A" },
  { id: 45, question: "5) What does the HTTP status code '404' mean?", options: ["A) OK", "B) Moved Permanently", "C) Not Found", "D) Bad Request"], answer: "C" },
  { id: 46, question: "6) Non-persistent HTTP allows sending multiple objects over a single TCP connection.", options: ["A) True", "B) False"], answer: "B" },
  { id: 47, question: "7) Which delay is variable and depends on network congestion?", options: ["A) Processing delay", "B) Transmission delay", "C) Queuing delay", "D) Propagation delay"], answer: "C" },
  { id: 48, question: "8) Web Caching (Proxy Server) helps reduce response time for client requests.", options: ["A) True", "B) False"], answer: "A" },
  { id: 49, question: "9) What is RTT?", options: ["A) Real Transfer Time", "B) Round Trip Time", "C) Router Transmission Time", "D) Resource Transfer Technology"], answer: "B" },
  { id: 50, question: "10) HTTP uses UDP as its underlying transport protocol.", options: ["A) True", "B) False"], answer: "B" },
  { id: 51, question: "11) In the 'Conditional GET' mechanism, which header is used?", options: ["A) If-Modified-Since", "B) Date", "C) User-Agent", "D) Content-Type"], answer: "A" },
  { id: 52, question: "12) Throughput is the rate at which bits are actually transferred between sender and receiver.", options: ["A) True", "B) False"], answer: "A" },
  { id: 53, question: "13) A 'Cookie' is used by websites to keep track of user state.", options: ["A) True", "B) False"], answer: "A" },
  { id: 54, question: "14) What is the default port for HTTP?", options: ["A) 443", "B) 21", "C) 80", "D) 25"], answer: "C" },
  { id: 55, question: "15) Propagation delay is the time it takes to push all packet bits onto the link.", options: ["A) True", "B) False"], answer: "B" },
  { id: 56, question: "16) Packet loss occurs when a router's buffer is full.", options: ["A) True", "B) False"], answer: "A" },
  { id: 57, question: "17) What is the response status code for 'OK'?", options: ["A) 400", "B) 200", "C) 301", "D) 505"], answer: "B" },
  { id: 58, question: "18) A Proxy server acts as both a client and a server.", options: ["A) True", "B) False"], answer: "A" },
  { id: 59, question: "19) Packet delay = d_proc + d_queue + d_trans + d_prop.", options: ["A) True", "B) False"], answer: "A" },
  { id: 60, question: "20) Persistent HTTP without pipelining takes 2 RTTs for each referenced object.", options: ["A) True", "B) False"], answer: "B" },

  // Lecture 4: DNS, Email & FTP
  { id: 61, question: "1) What is the primary function of DNS?", options: ["A) Transferring files", "B) Translating hostnames to IP addresses", "C) Sending emails", "D) Web browsing"], answer: "B" },
  { id: 62, question: "2) DNS is a centralized database system.", options: ["A) True", "B) False"], answer: "B" },
  { id: 63, question: "3) Which DNS server is the last resort and contains the actual mapping?", options: ["A) Root DNS server", "B) TLD DNS server", "C) Authoritative DNS server", "D) Local DNS server"], answer: "C" },
  { id: 64, question: "4) FTP uses two parallel TCP connections: Control and Data.", options: ["A) True", "B) False"], answer: "A" },
  { id: 65, question: "5) Which protocol is used to send email messages from a client to a server?", options: ["A) POP3", "B) IMAP", "C) SMTP", "D) HTTP"], answer: "C" },
  { id: 66, question: "6) Telnet is more secure than SSH because it encrypts all data.", options: ["A) True", "B) False"], answer: "B" },
  { id: 67, question: "7) Which DNS query type puts the burden of name resolution on the queried name server?", options: ["A) Iterative", "B) Recursive", "C) Hierarchical", "D) Distributed"], answer: "B" },
  { id: 68, question: "8) The Top-Level Domain (TLD) server is responsible for .com, .org, and .edu.", options: ["A) True", "B) False"], answer: "A" },
  { id: 69, question: "9) What is the port number for SMTP?", options: ["A) 80", "B) 25", "C) 110", "D) 21"], answer: "B" },
  { id: 70, question: "10) POP3 is a 'Download-and-Delete' protocol by default.", options: ["A) True", "B) False"], answer: "A" },
  { id: 71, question: "11) Unlike POP3, IMAP allows users to organize emails into folders on the server.", options: ["A) True", "B) False"], answer: "A" },
  { id: 72, question: "12) FTP's 'Control' connection is 'Out-of-Band.'", options: ["A) True", "B) False"], answer: "A" },
  { id: 73, question: "13) What is the default port for FTP Control?", options: ["A) 20", "B) 21", "C) 22", "D) 23"], answer: "B" },
  { id: 74, question: "14) DNS uses TCP as its transport protocol for queries.", options: ["A) True", "B) False"], answer: "B" },
  { id: 75, question: "15) Mail Access Protocols (like POP3/IMAP) are used to pull mail from the server.", options: ["A) True", "B) False"], answer: "A" },
  { id: 76, question: "16) Which DNS record type contains the hostname to IP address mapping?", options: ["A) NS", "B) CNAME", "C) Type A", "D) MX"], answer: "C" },
  { id: 77, question: "17) SMTP uses persistent connections.", options: ["A) True", "B) False"], answer: "A" },
  { id: 78, question: "18) Local DNS servers (provided by ISP) are not strictly part of the DNS hierarchy.", options: ["A) True", "B) False"], answer: "A" },
  { id: 79, question: "19) SSH stands for Secure Shell.", options: ["A) True", "B) False"], answer: "A" },
  { id: 80, question: "20) DNS caching helps improve performance by reducing the number of queries to the hierarchy.", options: ["A) True", "B) False"], answer: "A" },

  // Lecture 5: Transport Layer & TCP/UDP
  { id: 81, question: "1) The Transport Layer provides logical communication between ______?", options: ["A) Hosts", "B) Routers", "C) Processes", "D) Links"], answer: "C" },
  { id: 82, question: "2) UDP is a connection-oriented, reliable protocol.", options: ["A) True", "B) False"], answer: "B" },
  { id: 83, question: "3) Which protocol is used for applications like streaming video or DNS where speed is more important than reliability?", options: ["A) TCP", "B) IP", "C) UDP", "D) FTP"], answer: "C" },
  { id: 84, question: "4) The TCP Three-Way Handshake involves SYN, SYN-ACK, and ACK messages.", options: ["A) True", "B) False"], answer: "A" },
  { id: 85, question: "5) What does 'Flow Control' in TCP prevent?", options: ["A) Network congestion", "B) Sender overflowing the receiver's buffer", "C) Packet loss due to noise", "D) Unauthorized access"], answer: "B" },
  { id: 86, question: "6) UDP does not have a 'Checksum' field in its header.", options: ["A) True", "B) False"], answer: "B" },
  { id: 87, question: "7) Which field in the TCP header is used to ensure data is reassembled in the correct order?", options: ["A) Port Number", "B) Sequence Number", "C) Window Size", "D) Checksum"], answer: "B" },
  { id: 88, question: "8) Multiplexing is the job of gathering data chunks from different sockets and adding headers.", options: ["A) True", "B) False"], answer: "A" },
  { id: 89, question: "9) What is the size of a TCP header (without options)?", options: ["A) 8 bytes", "B) 16 bytes", "C) 20 bytes", "D) 32 bytes"], answer: "C" },
  { id: 90, question: "10) TCP provides 'Cumulative Acknowledgments.'", options: ["A) True", "B) False"], answer: "A" },
  { id: 91, question: "11) In TCP, the 'Window Size' field is used for congestion control only.", options: ["A) True", "B) False"], answer: "B" },
  { id: 92, question: "12) UDP header size is 8 bytes.", options: ["A) True", "B) False"], answer: "A" },
  { id: 93, question: "13) What is the purpose of the 'Timeout' in RDT (Reliable Data Transfer)?", options: ["A) To stop the connection", "B) To retransmit lost packets", "C) To increase speed", "D) To check for errors"], answer: "B" },
  { id: 94, question: "14) A TCP socket is identified by a 4-tuple: (Source IP, Source Port, Dest IP, Dest Port).", options: ["A) True", "B) False"], answer: "A" },
  { id: 95, question: "15) UDP provides 'Best-Effort' delivery.", options: ["A) True", "B) False"], answer: "A" },
  { id: 96, question: "16) Which protocol uses 'Congestion Control' to prevent the network from becoming overloaded?", options: ["A) UDP", "B) IP", "C) TCP", "D) HTTP"], answer: "C" },
  { id: 97, question: "17) Retransmission in TCP can be triggered by a timeout or triple duplicate ACKs.", options: ["A) True", "B) False"], answer: "A" },
  { id: 98, question: "18) Transport layer protocols run in the core routers.", options: ["A) True", "B) False"], answer: "B" },
  { id: 99, question: "19) TCP is 'Full Duplex,' meaning data can flow in both directions simultaneously.", options: ["A) True", "B) False"], answer: "A" },
  { id: 100, question: "20) The initial sequence number in TCP is always zero.", options: ["A) True", "B) False"], answer: "B" }
];

const QUESTIONS = [
  ...MCQ_DATA
];