const MCQ_DATA = [
  { id: 1, question: "1) The components of a computer system include:", options: ["A) Software", "B) Hardware", "C) User", "D) All the above"], answer: "D" },
  { id: 2, question: "2) What component of a computer system do END USERS interact with?", options: ["A) CPU", "B) Chache Memory", "C) Application Programs", "D) Non the above"], answer: "C" },
  { id: 3, question: "3) Application Programs are part of:", options: ["A) Software component", "B) Hardware component", "C) Operating System", "D) Non the above"], answer: "A" },
  { id: 4, question: "4) Describe the user modification ability for RAM and ROM:", options: ["A) RAM is user modified while ROM is not", "B) ROM is user modified while RAM is not", "C) Both RAM and ROM are user modified", "D) Neither RAM nor ROM are user modified"], answer: "A" },
  { id: 5, question: "5) Describe the relationship between CACHE MEMORY and processor speed:", options: ["A) Cache Memory decreases processor speed", "B) Cache Memory increases processor speed", "C) Cache Memory does not affect processor speed", "D) The effect cannot be measured"], answer: "B" },
  { id: 6, question: "6) ... is defined as the program running all the times on the computer to communicate with all the computer components:", options: ["A) Application Program", "B) Run Time Environment", "C) Compilers", "D) Operating System (OS)"], answer: "D" },
  { id: 7, question: "7) .......... is a system with more than one processor to maximize the system speed:", options: ["A) Batch System", "B) Multi-Processor System", "C) Multi-Programming System", "D) Real Time System"], answer: "B" },
  { id: 8, question: "8) All of these are activities supported by modern operating systems except for:", options: ["A) Process Management", "B) Memory Management", "C) File Management", "D) Cost Management"], answer: "D" },
  { id: 9, question: "9) Real Time Systems are categorized into:", options: ["A) Hard Real Time Systems", "B) Soft Real Time Systems", "C) Both A and B", "D) Non the above"], answer: "C" },
  { id: 10, question: "10) In which type of Operating system does MULTIPLE USERS share the CPU at the SAME TIME?", options: ["A) Batch System", "B) Multi-Tasking System", "C) Multi-Processor System", "D) Real Time System"], answer: "B" },
  { id: 16, question: "16) What is the main difference between a Program and a Process:", options: ["A) A Process is an active element while a Program is a passive element", "B) A Process is a passive element while a Program is an active element", "C) A Process is mostly passive while a Program is mostly active", "D) Non the above"], answer: "A" },
  { id: 17, question: "17) A Process can be described as:", options: ["A) A Program before execution", "B) A Program after execution", "C) A Program in execution", "D) Non the above"], answer: "C" },
  { id: 18, question: "18) A resource is:", options: ["A) Hardware used in the system by an active process", "B) Software used in the system by an active process", "C) Both A and B are correct", "D) Non the above"], answer: "C" },
  { id: 19, question: "19) Which of the following is NOT a process state:", options: ["A) Old", "B) Ready", "C) Running", "D) Terminated"], answer: "A" },
  { id: 20, question: "20) What are the different steps to utilize a resource by a process?", options: ["A) Request, Release then Use", "B) Request, Use then Release", "C) Release, Use then Request", "D) Release, Request then Use"], answer: "B" },
  { id: 21, question: "21) A Process Control Block (PCB) contains:", options: ["A) Process State", "B) Process Priority", "C) I/O information (i.e., Opened Files, I/O devices)", "D) All the above"], answer: "D" },
  { id: 22, question: "22) Context Switch can be defined as:", options: ["A) The time needed by the OS to load a program into the ready queue", "B) The time used by the OS to do useful work", "C) The time needed by the OS to switch the CPU from a process to another", "D) Non the above"], answer: "C" },
  { id: 26, question: "26) Some of the CPU Scheduling Methods are:", options: ["A) First Come First Serviced (FCFS)", "B) Shortest Job Firs (SJF)", "C) Priority Scheduling", "D) All the above"], answer: "D" },
  { id: 27, question: "27) In Preemptive Scheduling:", options: ["A) CPU CANNOT release a process if a process with higher priority comes", "B) CPU CAN release a process if a process with higher priority comes", "C) The CPU is allocated by a certain process until the process releases CPU", "D) Non the above"], answer: "B" },
  { id: 28, question: "28) System Throughput is defined as:", options: ["A) The number of processes that are completed per time unit", "B) The total time needed for process execution", "C) The sum of all periods the process spends waiting in the ready queue", "D) It is the time from the submission of a process until the first response is produced"], answer: "A" },
  { id: 29, question: "29) Turnaround Time is defined as:", options: ["A) The number of processes that are completed per time unit", "B) The total time needed for process execution", "C) The sum of all periods the process spends waiting in the ready queue", "D) It is the time from the submission of a process until the first response is produced"], answer: "B" },
  { id: 30, question: "30) Waiting Time is defined as:", options: ["A) The number of processes that are completed per time unit", "B) The total time needed for process execution", "C) The sum of all periods the process spends waiting in the ready queue", "D) It is the time from the submission of a process until the first response is produced"], answer: "C" },
  { id: 31, question: "31) Response Time is defined as:", options: ["A) The number of processes that are completed per time unit", "B) The total time needed for process execution", "C) The sum of all periods the process spends waiting in the ready queue", "D) It is the time from the submission of a process until the first response is produced"], answer: "D" },
  { id: 32, question: "32) It is desirable to Maximize............and minimize..........", options: ["A) Maximize CPU utilization and minimize Waiting Time", "B) Maximize Waiting Time and minimize CPU utilization", "C) Maximize Response Time and minimize System Throughput", "D) Non the above"], answer: "A" },
  { id: 33, question: "33) To Maximize CPU utilization, we need to:", options: ["A) Keep CPU as free as possible", "B) Keep CPU as busy as possible", "C) Keep RAM as free as possible", "D) Keep RAM as busy as possible"], answer: "B" },
  { id: 38, question: "38) Using SRTF, the average waiting time is:", options: ["A) 10", "B) 1.75", "C) 3.22", "D) 7"], answer: "B" },
  { id: 39, question: "39) Using SRTF, the average turnaround time is:", options: ["A) 6", "B) 17", "C) 4", "D) 25"], answer: "A" },
  { id: 40, question: "40) Using SRTF, the total execution time for all the processes is:", options: ["A) 14", "B) 17", "C) 15", "D) 20"], answer: "B" },
  { id: 41, question: "41) The execution sequence is :", options: ["a) P2,P3,P2,P1,P2,P2", "b) P1,P2,P3,P2,P1,P3", "c) P1,P2,P3,P1,P2,P2", "d) None of the above"], answer: "c" },
  { id: 42, question: "42) The waiting time of P2 is", options: ["a) 4", "b) 11", "c) 25", "d) 12"], answer: "b" },
  { id: 43, question: "43) The waiting time of P3 is", options: ["a) 4", "b) 11", "c) 25", "d) 12"], answer: "a" },
  { id: 44, question: "44) The turnaround time of P1 is", options: ["a) 4", "b) 11", "c) 25", "d) 12"], answer: "d" },
  { id: 45, question: "45) The average wait time is", options: ["a) 8.5", "b) 10.33", "c) 9.66", "d) 11"], answer: "b" },
  { id: 48, question: "48) The smallest division of a magnetic disk is:", options: ["A) Cylinder", "B) Track", "C) Sector", "D) Platte"], answer: "C" },
  { id: 50, question: "50) A Cylinder consists of a group of..........:", options: ["A) Disks", "B) Tracks", "C) Sectors", "D) Platters"], answer: "B" },
  { id: 51, question: "51) One of the parameters we can use to measure disk performance is:", options: ["A) Disk Access Time", "B) Waiting Time", "C) Turnaround Time", "D) Response Time"], answer: "A" },
  { id: 52, question: "52) The operating system is responsible for?", options: ["a) disk initialization", "b) booting from disk", "c) bad-block recovery", "d) all of the mentioned"], answer: "d" },
  { id: 54, question: "54) __________ may suffer from starvation of some requests.", options: ["a) FCFS Scheduling", "b) SSTF Scheduling", "c) C-Scan Scheduling", "d) C-Look Scheduling"], answer: "b" },
  { id: 56, question: "56) The data structure for a sector typically contains", options: ["a) header", "b) data area", "c) trailer", "d) all of the mentioned"], answer: "d" },
  { id: 58, question: "58) SSTF algorithm, like SJF", options: ["a) may cause starvation", "b) will cause starvation", "c) does not cause starvation", "d) causes aging"], answer: "a" },
  { id: 59, question: "59) In the __________ algorithm, the disk arm starts at one end... servicing requests... At the other end, the direction is reversed.", options: ["a) FCFS", "b) SCAN", "c) C-SCAN", "d) C-LOOK"], answer: "b" },
  { id: 60, question: "60) In the __________ algorithm... When the head reaches the other end, it immediately returns to the beginning without servicing.", options: ["a) SSTF", "b) SCAN", "c) C-SCAN", "d) C-LOOK"], answer: "c" },
  { id: 61, question: "61) What is the disk bandwidth?", options: ["a) the total number of bytes transferred", "b) total time between the first request...", "c) the total number of bytes transferred divided by the total time...", "d) none of the mentioned"], answer: "c" },
  { id: 62, question: "62) A Disk has 6 platters... assuming a sector's size is 256 bytes, the disk capacity is:", options: ["A) 768 MB", "B) 384 MB", "C) 768 KB", "D) 384 KB"], answer: "A" },
  { id: 63, question: "63) A disk has 6 platters and 5268 tracks per surface, how many tracks does the disk have?", options: ["A) 5,268", "B) 31,608", "C) 10,536", "D) 63,216"], answer: "D" },
  { id: 64, question: "64) SSTF (Shortest Seek Time First). total head movement for (98, 183, 37, 122, 14, 124, 65, 67) from 53:", options: ["a) 230 Cylinder.", "b) 153 Cylinder", "c) 236 Cylinder.", "d) 640 cylinder"], answer: "c" },
  { id: 67, question: "67) The three major methods of allocating disk space that are in wide use are", options: ["a) contiguous", "b) linked", "c) indexed", "d) all of the mentioned"], answer: "d" },
  { id: 68, question: "68) In contiguous file allocation", options: ["a) each file must occupy a set of contiguous blocks on the disk", "b) each file is a linked list of disk blocks", "c) all the pointers... placed together in one location", "d) none of the mentioned"], answer: "a" },
  { id: 69, question: "69) In linked allocation", options: ["a) each file must occupy a set of contiguous blocks on the disk", "b) each file is a linked list of disk blocks", "c) all the pointers... placed together in one location", "d) none of the mentioned"], answer: "b" },
  { id: 70, question: "70) In the linked allocation, the directory contains a pointer to which block?", options: ["a) I only (first block)", "b) II only (last block)", "c) Both I and II", "d) Neither I nor II"], answer: "c" },
  { id: 71, question: "71) There is no __________ with linked allocation.", options: ["a) internal fragmentation", "b) external fragmentation", "c) starvation", "d) all of the mentioned"], answer: "b" },
  { id: 72, question: "72) In indexed allocation", options: ["a) occupy contiguous blocks", "b) linked list of disk blocks", "c) all the pointers... placed together in one location", "d) none of the mentioned"], answer: "c" },
  { id: 73, question: "73) Contiguous allocation of a file is defined by", options: ["a) disk address of the first block & length", "b) length & size of the block", "c) size of the block", "d) total size of the file"], answer: "a" },
  { id: 76, question: "76) __________ allows any blocks to be read or written in no order.", options: ["a) Direct access method", "b) Indexed access method", "c) Both a and b", "d) None of the mentioned"], answer: "a" },
  { id: 80, question: "80) An address generated by the CPU is known as address... memory unit is referred as address.", options: ["a) physical, logical", "b) logical, virtual", "c) virtual, logical", "d) logical, physical"], answer: "d" },
  { id: 81, question: "81) Run time mapping from virtual to physical address is done by", options: ["a) Memory management unit", "b) CPU", "c) PCI", "d) None of the mentioned"], answer: "a" },
  { id: 83, question: "83) What is compaction?", options: ["a) overcoming internal fragmentation", "b) a paging technique", "c) overcoming external fragmentation", "d) overcoming fatal error"], answer: "c" },
  { id: 84, question: "84) A solution to the problem of external fragmentation is", options: ["a) compaction", "b) larger memory space", "c) smaller memory space", "d) none of the mentioned"], answer: "a" },
  { id: 85, question: "85) The __________ swaps processes in and out of the memory.", options: ["a) Memory manager", "b) CPU", "c) CPU manager", "d) User"], answer: "a" },
  { id: 86, question: "86) Swapping requires a", options: ["a) motherboard", "b) keyboard", "c) monitor", "d) backing store"], answer: "d" },
  { id: 87, question: "87) The backing store is generally a", options: ["a) fast disk", "b) disk large enough for all memory images", "c) direct access to images", "d) all of the mentioned"], answer: "d" },
  { id: 88, question: "88) The major part of swap time is __________ time.", options: ["a) waiting", "b) transfer", "c) execution", "d) none of the mentioned"], answer: "b" },
  { id: 89, question: "89) In contiguous memory allocation", options: ["a) each process is contained in a single contiguous section", "b) all processes in one section", "c) memory space is contiguous", "d) none of the mentioned"], answer: "a" },
  { id: 90, question: "90) The relocation register helps in", options: ["a) more address space", "b) different address space", "c) protect the address spaces", "d) none of the mentioned"], answer: "c" },
  { id: 91, question: "91) When memory is divided into fixed sized partitions, each may contain", options: ["a) exactly one process", "b) at least one process", "c) multiple processes at once", "d) none of the mentioned"], answer: "a" },
  { id: 92, question: "92) The first fit, best fit and worst fit are strategies to select a", options: ["a) process from a queue", "b) processor", "c) free hole from a set of available holes", "d) all of the mentioned"], answer: "c" },
  { id: 93, question: "93) __________ is generally faster than __________ and __________", options: ["a) first fit, best fit, worst fit", "b) best fit, first fit, worst fit", "c) worst fit, best fit, first fit", "d) none of the mentioned"], answer: "a" },
  { id: 94, question: "94) Contiguous memory allocation having variable size partition suffers from:", options: ["a) external fragmentation", "b) internal fragmentation", "c) both external and internal fragmentation", "d) none of the mentioned"], answer: "a" },
  { id: 98, question: "98) External fragmentation will not occur when?", options: ["a) first fit is used", "b) best fit is used", "c) worst fit is used", "d) it will always occur (in contiguous allocation)"], answer: "d" },
  { id: 99, question: "99) The size of a process is limited to the size of", options: ["a) physical memory", "b) external storage", "c) secondary storage", "d) none of the mentioned"], answer: "a" },
  { id: 100, question: "100) The __________ time in a swap out/in... is very high.", options: ["a) context switch", "b) waiting", "c) execution", "d) all of the mentioned"], answer: "a" },
  { id: 101, question: "101) Another solution to the problem of external fragmentation problem is to", options: ["a) permit the logical address space of a process to be noncontiguous", "b) smaller processes at last", "c) larger processes at last", "d) all of the mentioned"], answer: "a" },
  { id: 102, question: "102) In fixed size partition, the degree of multiprogramming is bounded by", options: ["a) the number of partitions", "b) the CPU utilization", "c) the memory size", "d) all of the mentioned"], answer: "a" },
  { id: 103, question: "103) The base register is also known as the", options: ["a) basic register", "b) regular register", "c) relocation register", "d) delocation register"], answer: "c" },
  { id: 110, question: "110) The OS and processes are protected... because", options: ["a) different memory spaces", "b) different logical addresses", "c) protection algorithm", "d) every address checked against relocation and limit registers"], answer: "d" },
  { id: 112, question: "112) Dividing a disk into sectors... before store data is known as", options: ["a) partitioning", "b) swap space creation", "c) low-level formatting", "d) none of the mentioned"], answer: "c" },
  { id: 113, question: "113) ...........is to keep data safe from improper access by controlling file operations...", options: ["a) Data protection", "b) Data reliability", "c) Both a and b", "d) None of the mentioned"], answer: "a" },
  { id: 114, question: "114) Another name for logical address is", options: ["a) virtual address", "b) physical address", "c) absolute address", "d) none of the mentioned"], answer: "a" },
];

const TF_DATA = [
  { id: 11, question: "11) RAM, ROM and Cache Memory are a part of secondary storage", options: ["a) True", "b) False"], answer: "b" },
  { id: 13, question: "13) Both Application Programs and Operating Systems are hardware components", options: ["a) True", "b) False"], answer: "b" },
  { id: 14, question: "14) Output units show the result of a process", options: ["a) True", "b) False"], answer: "a" },
  { id: 15, question: "15) RAM is volatile memory", options: ["a) True", "b) False"], answer: "a" },
  { id: 23, question: "23) The process state New, means that the process is being created", options: ["a) True", "b) False"], answer: "a" },
  { id: 24, question: "24) If an interrupt occurs, the state of process goes back from Running to Ready", options: ["a) True", "b) False"], answer: "a" },
  { id: 25, question: "25) The Long-Term Scheduler determines the degree of multi-programming", options: ["a) True", "b) False"], answer: "a" },
  { id: 34, question: "34) Starvation is a problem that faces FCFS Scheduling", options: ["a) True", "b) False"], answer: "b" },
  { id: 35, question: "35) Increasing the Quantum in Quantum Scheduling increases the context switch", options: ["a) True", "b) False"], answer: "b" },
  { id: 46, question: "46) FCFS Scheduling results in a long waiting time for small processes", options: ["a) True", "b) False"], answer: "a" },
  { id: 47, question: "47) First Come First Serviced (FCFS) is non-preemptive", options: ["a) True", "b) False"], answer: "a" },
  { id: 65, question: "65) The block is the smallest unit of data transfer, while the sector is the smallest storage unit.", options: ["a) True", "b) False"], answer: "a" },
  { id: 66, question: "66) Disk formatting prepares a storage device for initial use... low-level formatting, partitioning...", options: ["a) True", "b) False"], answer: "a" },
  { id: 77, question: "77) Sequential access allows reading or writing to any block in a file in no particular order.", options: ["a) True", "b) False"], answer: "b" },
  { id: 78, question: "78) Indexed access utilizes an index with pointers to blocks, improving read speeds.", options: ["a) True", "b) False"], answer: "a" },
  { id: 95, question: "95) Base and limit registers help protect the OS and user processes by defining allowed memory ranges.", options: ["a) True", "b) False"], answer: "a" },
  { id: 96, question: "96) The logical address is the address seen by the memory unit", options: ["a) True", "b) False"], answer: "b" },
  { id: 105, question: "105) A sector address consists of cylinder number, surface number, and sector number.", options: ["a) True", "b) False"], answer: "a" },
  { id: 106, question: "106) A hard disk with 6 plates has 6 tracks per cylinder.", options: ["a) True", "b) False"], answer: "a" },
  { id: 107, question: "107) Inter-sector gaps are included to prevent data interference between sectors.", options: ["a) True", "b) False"], answer: "a" },
  { id: 108, question: "108) Disk bandwidth is the time it takes to read or write to disk.", options: ["a) True", "b) False"], answer: "b" },
  { id: 111, question: "111) The relocation register is used to protect user programs from each other.", options: ["a) True", "b) False"], answer: "a" },
  { id: 119, question: "119) Schedulers can be classified into Long-Term and Short Term only", options: ["a) True", "b) False"], answer: "b" },
  { id: 120, question: "120) The Medium-Term Scheduler increases the degree of multiprogramming", options: ["a) True", "b) False"], answer: "b" },
  { id: 123, question: "123) Increasing the Quantum in Quantum Scheduling increases the context switch", options: ["a) True", "b) False"], answer: "b" },
  { id: 124, question: "124) In SJF Scheduling, the process that comes first will be executed first", options: ["a) True", "b) False"], answer: "b" },
  { id: 125, question: "125) Hard Real Time Systems, critical tasks get priority over other tasks", options: ["a) True", "b) False"], answer: "b" },
  { id: 128, question: "128) Magnetic disks can be divided into tracks and sectors", options: ["a) True", "b) False"], answer: "a" },
];
const QUESTIONS = [
  ...MCQ_DATA,
  ...TF_DATA
];